import assert from 'node:assert/strict';
import * as THREE from 'three';
import runtime from './player.cjs';
import {blocked,foldsAt} from './tile-model.mjs';
import {validateRegions,taggedCells,regionOf,migrateRegions} from './regions.mjs';
import {uniqueFoldAxes,foldGroupAt,inFoldRange} from './fold-geometry.mjs';
import {createTerrainState,canEnterTerrain,enterTerrain,finishAction,validateTerrains} from './special-terrain.mjs';
const map={width:5,height:5,tiles:Array.from({length:5},()=>Array(5).fill(null)),spawn:{r:0,c:0,dir:2},exit:null,maxSteps:0,bestSteps:null};
for(const [r,c,regionTag,tags] of [[0,0,'A',{spawn:true}],[0,1,'A',{exitTo:'B'}],[1,0,'A',{}],[3,3,'B',{entry:true}],[3,4,'B',{}]])map.tiles[r][c]={color:'white',regionTag,tags,height:.09,blocked:false};
const P=runtime.createPlayerState(map.spawn),nodes=new Map(),group=new THREE.Group(),ring={},noop=()=>{};
const inside=(r,c)=>r>=0&&c>=0&&r<5&&c<5;
const isHidden=(r,c)=>P.mode==='play'&&map.tiles[r]?.[c]&&!P.revealedRegions.has(regionOf(map.tiles[r][c]));
const walkable=(r,c)=>inside(r,c)&&!!map.tiles[r][c]&&!blocked(map.tiles[r][c])&&!isHidden(r,c)&&map.tiles[r][c].terrain!=='campfire';
let controller;
const env={state:P,THREE,$:id=>{if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);},getMap:()=>map,getFoldAxes:()=>uniqueFoldAxes(map),getPlayerGroup:()=>group,getSelectionRing:()=>ring,getEffectLayer:()=>new THREE.Group(),invalidateAxes:noop,isHidden,blocked,inside,walkable,canEnterTerrain,enterTerrain,finishAction,createTerrainState,validateTerrains,validateRegions,taggedCells,regionOf,foldsAt,inFoldRange,foldGroupAt,coord:(r,c)=>`${r},${c}`,FOLD_NAMES:{},clone:structuredClone,persist:noop,toast:noop,record:()=>P.playHistory.push(controller.snapshot()),updateUI:noop,buildPaper:noop,renderPlayer:noop,disposableClear:noop,overlay:noop,tileOutline:noop,wx:c=>c,wz:r=>r,tileTop:()=>.09};
controller=runtime.createPlayerController(env);controller.resetRegions();assert.equal(controller.validateForPlay().valid,true);
controller.setMode('play');assert.deepEqual([...P.revealedRegions],['A']);assert.equal(controller.canMoveTo(3,3),false);
controller.click(3,4);assert.deepEqual(P.player,{r:0,c:0,dir:2});assert.equal(P.legalMoves.length,0);
controller.click(0,0);assert.equal(P.legalMoves.length,2);controller.movePlayer(0,1);
assert.deepEqual(P.player,{r:3,c:3,dir:2});assert.deepEqual([...P.revealedRegions],['A','B']);assert.equal(P.steps,1);assert.equal(P.animation.type,'teleport');assert.equal(controller.canMoveTo(3,4),true);
controller.tick(performance.now()+1000);assert.equal(P.moving,false);
const snapshot=controller.snapshot();snapshot.revealedRegions.push('unrelated');assert.equal(P.revealedRegions.has('unrelated'),false);
controller.restore(P.playHistory.pop());assert.deepEqual(P.player,map.spawn);assert.deepEqual([...P.revealedRegions],['A']);assert.equal(P.steps,0);
controller.click(0,0);controller.movePlayer(0,1);controller.tick(performance.now()+1000);controller.restart();assert.deepEqual([...P.revealedRegions],['A']);assert.equal(P.playHistory.length,0);assert.deepEqual(P.player,map.spawn);
controller.turn(-1);assert.equal(P.player.dir,1);
controller.setMode('edit');assert.deepEqual(P.player,map.spawn);
const bad=structuredClone(map);bad.tiles[1][0].tags={entry:true};assert.ok(validateRegions(bad).length);
console.log('PASS: player-only control, initial region, cumulative transitions, terrain actions, animation, independent snapshots, undo, restart and facing.');
